// This file is generated by ./make.dart

class BuildData {
  static const String name = "ServerBox";
  static const int build = 552;
  static const String engine = "3.13.2";
  static const String buildAt = "2023-09-15 16:36:09";
  static const int modifications = 62;
  static const int script = 15;
}
